os: linux
dist: focal
services:
  - docker

before_install:
  # Build all the images
  - cd v2.31.6
  - docker build -t ud-viz:demofull-apache DemoFull-Apache
  - docker build -t ud-viz:demofull-simpleserver DemoFull-SimpleServer
  - docker build -t ud-viz:imuv Imuv
  - docker build -t ud-viz:imuv-editor ImuvEditor

